apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  DB_HOST: db
  DB_PORT: "3306" 
  REDIS_HOST: redis
  REDIS_USER: redis 
  AUTH_HOST: auth 
  AUTH_PORT: "8080"
  WEATHER_HOST: weather
  WEATHER_PORT: "5000"
