apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpha-weather
  template:
    metadata:
      labels:
        app: alpha-weather
    spec:
      initContainers:
        - name: init-db
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z db 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
      containers:
        - name: alpha-weather
          image: proudevops/weather:1.0.1 
          imagePullPolicy: Always 
          env:
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets-asm
                  key: APIKEY
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: weather
spec:
  selector:
    app: alpha-weather
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
